"""empty message

Revision ID: a0b0d121bfb3
Revises: 
Create Date: 2025-02-17 19:55:10.123448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0b0d121bfb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_table', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=mysql.VARCHAR(length=9000),
               nullable=False)
        batch_op.alter_column('option_a',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.alter_column('option_b',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.alter_column('option_c',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.alter_column('option_d',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.alter_column('answer',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_table', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('option_d',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('option_c',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('option_b',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('option_a',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('question',
               existing_type=mysql.VARCHAR(length=9000),
               nullable=True)

    # ### end Alembic commands ###
